spring:
  logging:
    file: Documents/logs/application.txt
    level:
      root: info  # Correctly indented
  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: root@root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Can be create, create-drop, update, validate
    show-sql: true     # To display SQL statements in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
